# %%%%%%%%%%%%%%%%%%%%
# [os-linux-rhel] 变量文件
# %%%%%%%%%%%%%%%%%%%%
# - PS: 
#   在每个角色中，不同的任务的启用与否，不再通过代码注释，而是通过 enabled 变量去控制
#   在每个角色的变量文件中，定义变量，并设置默认值。
#   在具体脚本拼接角色去实现特定的流程与功能的时候，再最终定义不同场景中的变量的值


# ===================== Task Switch

# OS User and Group
# os_user_and_group_enabled: yes

# OS Directory
# os_directory_enabled: yes

# OS Hosts
# os_host_enabled: yes

# OS Network
# os_network_enabled: yes

# OS SSH Connectivity
# os_ssh_connectivity_enabled: yes

# Python
# python_enabled: yes

# ===================== [os_user_and_group.yml]

# os_user_and_group__group:
#   - name: "oinstall"
#     id: 4001
#   - name: "dba"
#     id: 4002
#   - name: "asmdba"
#     id: 4003
#   - name: "asmadmin"
#     id: 4004

# os_user_and_group__user:
#   - username: "oracle"
#     password: "oracle"
#     comment: "Oracle Database User"
#     id: 4005
#     shell: "/bin/bash"
#     dir_home: "/home/oracle"
#     group: "oinstall"
#     groups:
#       - "dba"
#       - "asmdba"
#   - username: "grid"
#     password: "oracle"
#     comment: "Grid Infrastructure User"
#     id: 4005
#     shell: "/bin/bash"
#     dir_home: "/home/oracle"
#     group: "oinstall"
#     groups:
#       - "dba"
#       - "asmdba"
#       - "asmadmin"

# os_user_and_group__environment:
#   # 数据库用户【oracle】
#   - user: 'oracle'
#     key: 'ORACLE_SID'
#     value: '{{ var__oracle_sid }}{{ node_id }}'
#   - user: 'oracle'
#     key: 'ORACLE_BASE'
#     value: '{{ dir__oracle_base }}'
#   - user: 'oracle'
#     key: 'ORACLE_HOME'
#     value: '{{ dir__oracle_home }}'
#   - user: 'oracle'
#     key: 'PATH'
#     value: '$ORACLE_HOME/bin:$PATH:/sbin'
#   - user: 'oracle'
#     key: 'LD_LIBRARY_PATH'
#     value: '$ORACLE_HOME/lib:$LD_LIBRARY_PATH'
#   # 集群用户【grid】
#   - user: 'grid'
#     key: 'ORACLE_SID'
#     value: '+ASM{{ node_id }}'
#   - user: 'grid'
#     key: 'ORACLE_BASE'
#     value: '{{ dir__grid_base }}'
#   - user: 'grid'
#     key: 'ORACLE_HOME'
#     value: '{{ dir__grid_home }}'
#   - user: 'grid'
#     key: 'PATH'
#     value: '$ORACLE_HOME/bin:$PATH:/sbin'
#   - user: 'grid'
#     key: 'LD_LIBRARY_PATH'
#     value: '$ORACLE_HOME/lib:$LD_LIBRARY_PATH'

# ===================== [os_directory.yml]

# os_directory__directory:
#   - path: ""
#     owner: ""
#     group: ""
#     mode: ""

# ===================== [os_hosts.yml]

# --- simple
# deploy_hosts: "db-oracle-rac"
# os_host__comment: "# Add"

# --- complex
# # --- node1
# node1_hostname_public: "node1"

# # --- node2
# node2_hostname_public: "node2"

# os_host__hostname_ipaddr:
#   # --- node1
#   - hostname: "{{ node1_hostname_public }}"
#     ipaddr: "192.168.2.18"
#     node_id: 1
#   - hostname: "{{ node1_hostname_public }}-vip"
#     ipaddr: "10.10.10.11"
#     node_id: 1
#   - hostname: "{{ node1_hostname_public }}-priv-1"
#     ipaddr: "10.10.10.11"
#     node_id: 1
#   - hostname: "{{ node1_hostname_public }}-priv-2"
#     ipaddr: "10.10.10.11"
#     node_id: 1
#   # --- node2
#   - hostname: "{{ node2_hostname_public }}"
#     ipaddr: "192.168.2.20"
#     node_id: 2
#   - hostname: "{{ node2_hostname_public }}-vip"
#     ipaddr: "10.10.10.11"
#     node_id: 2
#   - hostname: "{{ node2_hostname_public }}-priv-1"
#     ipaddr: "10.10.10.11"
#     node_id: 2
#   - hostname: "{{ node2_hostname_public }}-priv-2"
#     ipaddr: "10.10.10.11"
#     node_id: 2
#   # --- other
#   - hostname: "scan1"
#     ipaddr: ""
#     node_id: "all"

# ===================== [os_network.yml]

# os_network__network_interfaces:
#   - category: "public"
#     nic_name: "ens192"
#   - category: "private1"
#     nic_name: "ens224"
#   - category: "private2"
#     nic_name: "ens256"

# ===================== [python.yml]
