# %%%%%%%%%%%%%%%%%%%%
# [os-linux-rhel] 变量文件
# %%%%%%%%%%%%%%%%%%%%
# - PS: 
#   在每个角色中，不同的任务的启用与否，不再通过代码注释，而是通过 enabled 变量去控制
#   在每个角色的变量文件中，定义变量，并设置默认值。
#   在具体脚本拼接角色去实现特定的流程与功能的时候，再最终定义不同场景中的变量的值


# ===================== Task Switch

# OS User and Group
# os_user_and_group_enabled: yes

# OS Directory
# os_directory_enabled: yes

# OS Hosts
# os_host_enabled: yes

# OS Network
# os_network_enabled: yes
# os_network_connections_refresh_and_config_enabled: yes

# OS SSH Connectivity
# os_ssh_connectivity_enabled: yes

# OS YUM
# os_yum_enabled: yes

# OS Linux Service
# os_service_enabled: yes

# OS Linux SELinux
# os_selinux_enabled: yes

# OS Linux Time
# os_time_enabled: yes
# os_time__ntp_enabled: yes

# OS Grub
# os_grub_enabled: yes

# OS Linux Kernel Parameters
# os_kernel_parameters_enabled: yes

# OS/ Storage / iSCSI discovery
# os_iscsi_discovery_enabled: yes

# OS / Storage / Multipath
# os_multipath_enabled: yes
# os_multipath_storage_dd_if_enabled: yes

# Python
# python_enabled: yes

# ===================== [os_user_and_group.yml]

# os_user_and_group__group:
#   - name: "oinstall"
#     id: 4001
#   - name: "dba"
#     id: 4002
#   - name: "asmdba"
#     id: 4003
#   - name: "asmadmin"
#     id: 4004

# os_user_and_group__user:
#   - username: "oracle"
#     password: "oracle"
#     comment: "Oracle Database User"
#     id: 4005
#     shell: "/bin/bash"
#     dir_home: "/home/oracle"
#     group: "oinstall"
#     groups:
#       - "dba"
#       - "asmdba"
#   - username: "grid"
#     password: "oracle"
#     comment: "Grid Infrastructure User"
#     id: 4005
#     shell: "/bin/bash"
#     dir_home: "/home/oracle"
#     group: "oinstall"
#     groups:
#       - "dba"
#       - "asmdba"
#       - "asmadmin"

# os_user_and_group__environment:
#   # 数据库用户【oracle】
#   - user: 'oracle'
#     key: 'ORACLE_SID'
#     value: '{{ var__oracle_sid }}{{ node_id }}'
#   - user: 'oracle'
#     key: 'ORACLE_BASE'
#     value: '{{ dir__oracle_base }}'
#   - user: 'oracle'
#     key: 'ORACLE_HOME'
#     value: '{{ dir__oracle_home }}'
#   - user: 'oracle'
#     key: 'PATH'
#     value: '$ORACLE_HOME/bin:$PATH:/sbin'
#   - user: 'oracle'
#     key: 'LD_LIBRARY_PATH'
#     value: '$ORACLE_HOME/lib:$LD_LIBRARY_PATH'
#   # 集群用户【grid】
#   - user: 'grid'
#     key: 'ORACLE_SID'
#     value: '+ASM{{ node_id }}'
#   - user: 'grid'
#     key: 'ORACLE_BASE'
#     value: '{{ dir__grid_base }}'
#   - user: 'grid'
#     key: 'ORACLE_HOME'
#     value: '{{ dir__grid_home }}'
#   - user: 'grid'
#     key: 'PATH'
#     value: '$ORACLE_HOME/bin:$PATH:/sbin'
#   - user: 'grid'
#     key: 'LD_LIBRARY_PATH'
#     value: '$ORACLE_HOME/lib:$LD_LIBRARY_PATH'

# ===================== [os_directory.yml]

# os_directory__directory:
#   - path: ""
#     owner: ""
#     group: ""
#     mode: ""

# ===================== [os_hosts.yml]

# --- simple
# deploy_hosts: "db-oracle-rac"
# os_host__comment: "# Add"

# --- complex
# # --- node1
# node1_hostname_public: "node1"

# # --- node2
# node2_hostname_public: "node2"

# # --- total
# os_host__hostname_ipaddr:
#   # --- node1
#   # 业务网段：public ip
#   - hostname: "{{ node1_hostname_public }}"
#     ipaddr: "192.168.2.18"
#     node_id: 1
#   # 业务网段：virtual ip / vip
#   - hostname: "{{ node1_hostname_public }}-vip"
#     ipaddr: "10.10.10.11"
#     node_id: 1
#   # 私有网段（1）：private ip 1
#   - hostname: "{{ node1_hostname_public }}-priv-1"
#     ipaddr: "10.10.10.11"
#     node_id: 1
#   # 私有网段（2）：private ip 2
#   - hostname: "{{ node1_hostname_public }}-priv-2"
#     ipaddr: "10.10.10.11"
#     node_id: 1
#   # --- node2
#   - hostname: "{{ node2_hostname_public }}"
#     ipaddr: "192.168.2.20"
#     node_id: 2
#   - hostname: "{{ node2_hostname_public }}-vip"
#     ipaddr: "10.10.10.11"
#     node_id: 2
#   - hostname: "{{ node2_hostname_public }}-priv-1"
#     ipaddr: "10.10.10.11"
#     node_id: 2
#   - hostname: "{{ node2_hostname_public }}-priv-2"
#     ipaddr: "10.10.10.11"
#     node_id: 2
#   # --- other
#   - hostname: "scan1"
#     ipaddr: ""
#     node_id: "all"

# ===================== [os_network.yml]

# os_network__network_interfaces:
#   # --- 绑定网卡
#   - category: "bond"
#     nic_name: "bond0"
#   # --- 业务网段：主网卡
#   - category: "public"
#     nic_name: "ens192"
#   # --- 业务网段：副网卡
#   - category: "public"
#     nic_name: "ens161"
#   # --- 私有网段（1）：主网卡
#   - category: "private1"
#     nic_name: "ens224"
#   # --- 私有网段（2）：主网卡
#   - category: "private2"
#     nic_name: "ens256"

# ===================== [os_yum.yml]

# os_yum__rpm_list:
#   - file: "rpm/compat-libstdc++-33-3.2.3-72.el7.x86_64.rpm"
#     name: "compat-libstdc++-33-3.2.3-72.el7.x86_64.rpm"
#   - file: "rpm/cvuqdisk-1.0.10-1.rpm"
#     name: "cvuqdisk-1.0.10-1.rpm"

# os_yum__repofile_list:
#   - file: "yum_repofile/local.repo.j2"
#     name: "local.repo"
#   # - file: "yum_repofile/centos-7-local.repo"
#   #   name: "local.repo"
#   # - file: "yum_repofile/centos-7.repo"
#   #   name: "local.repo"
#   # - file: "yum_repofile/epel-7.repo"
#   #   name: "local.repo"

# os_yum__install_list:
#   - bc
#   - binutils
#   - compat-libcap1
#   - device-mapper
#   - device-mapper-multipath
#   - elfutils-libelf
#   - elfutils-libelf-devel
#   - expat
#   - expect
#   - expect-devel
#   - gcc
#   - gcc-c++
#   - glibc
#   - glibc-devel
#   - glibc-common
#   - glibc-headers
#   - ksh
#   - libxcb
#   - libXau
#   - libXi
#   - libX11
#   - libXext
#   - libXtst
#   - libXrender
#   - libaio
#   - libaio-devel
#   - libgcc
#   - libstdc++
#   - libstdc++-devel
#   - make
#   - net-tools
#   - nfs-utils
#   - psmisc
#   - pexpect
#   - python2-pip
#   - python3-pip
#   - python3-devel
#   - python36-netaddr
#   - sysstat
#   - smartmontools
#   - tree
#   - unzip
#   - xorg-x11-server-utils

# ===================== [os_service.yml]

# os_service__service_list:
#   - "avahi-daemon"
#   - "firewalld"

# ===================== [os_selinux.yml]

# ===================== [os_time.yml]

# os_time__timezone: "Asia/Shanghai"
# os_time__ntp_server:
#   - 0.centos.pool.ntp.org
#   - ntp.aliyun.com
#   - ntp.tencent.com

# ===================== [os_grub.yml]

# ===================== [os_kernel_parameters.yml]

# list__os_sysctl:
#   # --- vm
#   # vm.overcommit_memory: 1
#   vm.nr_hugepages: '{{ linux_command_kernel_param__hugepages.stdout }}'
#   vm.swappiness: 5
#   # --- kernel
#   kernel.shmall: "{{ linux_command_kernel_param__shmall.stdout }}"
#   kernel.shmmax: "{{ linux_command_kernel_param__shmmax.stdout }}"
#   kernel.shmmni: 4096
#   kernel.sem: 1024 70000 1024 256
#   # --- net core rmem
#   net.core.rmem_default: 262144
#   net.core.rmem_max: 4194304
#   # --- net core wmem
#   net.core.wmem_default: 262144
#   net.core.wmem_max: 1048576
#   # --- net ip local port range
#   net.ipv4.ip_local_port_range: 9000 65500
#   # --- net rp_filter
#   # net.ipv4.conf.enp0s8.rp_filter: 2
#   # net.ipv4.conf.enp0s9.rp_filter: 2
#   # --- net ipfrag
#   net.ipv4.ipfrag_high_thresh: 41943040 
#   net.ipv4.ipfrag_low_thresh: 40894464 
#   net.ipv4.ipfrag_max_dist: 1024 
#   net.ipv4.ipfrag_secret_interval: 600
#   net.ipv4.ipfrag_time: 120
#   # --- fs
#   fs.file-max: 6815744
#   fs.aio-max-nr: 1048576

# list__os_limits:
#   # --- nofile
#   - dest: "/etc/security/limits.conf"
#     domain: "oracle"
#     limit_type: "soft"
#     limit_item: "nofile"
#     value: "65536"
#   - dest: "/etc/security/limits.conf"
#     domain: "oracle"
#     limit_type: "hard"
#     limit_item: "nofile"
#     value: "65536"
#   - dest: "/etc/security/limits.conf"
#     domain: "grid"
#     limit_type: "soft"
#     limit_item: "nofile"
#     value: "65536"
#   - dest: "/etc/security/limits.conf"
#     domain: "grid"
#     limit_type: "hard"
#     limit_item: "nofile"
#     value: "65536"
#   # --- nproc
#   - dest: "/etc/security/limits.conf"
#     domain: "oracle"
#     limit_type: "soft"
#     limit_item: "nproc"
#     value: "16384"
#   - dest: "/etc/security/limits.conf"
#     domain: "oracle"
#     limit_type: "hard"
#     limit_item: "nproc"
#     value: "16384"
#   - dest: "/etc/security/limits.conf"
#     domain: "grid"
#     limit_type: "soft"
#     limit_item: "nproc"
#     value: "16384"
#   - dest: "/etc/security/limits.conf"
#     domain: "grid"
#     limit_type: "hard"
#     limit_item: "nproc"
#     value: "16384"
#   # --- stack
#   - dest: "/etc/security/limits.conf"
#     domain: "oracle"
#     limit_type: "soft"
#     limit_item: "stack"
#     value: "10240"
#   - dest: "/etc/security/limits.conf"
#     domain: "oracle"
#     limit_type: "hard"
#     limit_item: "stack"
#     value: "32768"
#   - dest: "/etc/security/limits.conf"
#     domain: "grid"
#     limit_type: "soft"
#     limit_item: "stack"
#     value: "10240"
#   - dest: "/etc/security/limits.conf"
#     domain: "grid"
#     limit_type: "hard"
#     limit_item: "stack"
#     value: "32768"
#   # --- memlock
#   - dest: "/etc/security/limits.conf"
#     domain: "oracle"
#     limit_type: "soft"
#     limit_item: "memlock"
#     value: "{{ linux_command_kernel_param__memlock.stdout }}"
#   - dest: "/etc/security/limits.conf"
#     domain: "oracle"
#     limit_type: "hard"
#     limit_item: "memlock"
#     value: "{{ linux_command_kernel_param__memlock.stdout }}"

# ===================== [os_iscsi_discovery.yml]

# os_iscsi_discovery__iscsi_server_ip: "192.168.2.21"

# # 关系列表：磁盘的WWID 与 别名（LUN别名/多路径别名）
# os_iscsi_discovery__storage_wwid_and_alias:
#   # 磁盘组：OCR
#   - wwid: "14f504e46494c455258714c6349372d3533345a2d4c326475"
#     alias: "asm_ocr01"
#   - wwid: "14f504e46494c455275544b32466e2d51714c792d46623352"
#     alias: "asm_ocr02"
#   - wwid: "14f504e46494c4552314c476159782d416d47572d31336b48"
#     alias: "asm_ocr03"
#   # 磁盘组：DATA
#   - wwid: "14f504e46494c45527846583064622d614936572d4c355950"
#     alias: "asm_data01"
#   # 磁盘组：REDO
#   - wwid: "14f504e46494c45526e67586a4d422d624432562d6d494375"
#     alias: "asm_redo01"
#   # 磁盘组：ARCH
#   - wwid: "14f504e46494c4552574a626864792d343759302d6c454e79"
#     alias: "asm_fra01"

# ===================== [os_multipath.yml]

# ===================== [os_network_connections_refresh_and_config.yml]

# ===================== [python.yml]
