- name: "[os_directory.yml] create directories"
  file:
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    path: "{{ item.path }}"
  with_items: 
    - "{{ os_directory__directory }}"
