# ===================== RPMs

- name: "[os_yum.yml] RPMs / upload"
  copy:
    backup: yes
    force: yes
    owner: root
    group: root
    mode: 0755
    src: "{{ item.file }}"
    dest: "{{ dir__oracle_upload_rpm }}/{{ item.name }}"
  with_items:
   - "{{ os_yum__rpm_list }}"

- name: "[os_yum.yml] RPMs / install"
  shell: |
    rpm -ivh {{ dir__oracle_upload_rpm }}/{{ item.name }}
  with_items: 
   - "{{ os_yum__rpm_list }}"
  ignore_errors: yes

# ===================== YUM 打开本地缓存

- name: "[os_yum.yml] yum.conf / keepcache enable"
  lineinfile:
    backup: yes
    backrefs: no
    dest: /etc/yum.conf
    regexp: '^keepcache'
    line: 'keepcache=1'

# ===================== YUM / repofile / 备份

- name: "[os_yum.yml] YUM / repofile / copy"
  shell: |
    cp /etc/yum.repos.d/*.repo {{ dir__oracle_upload_yum_repofile }}
  ignore_errors: yes

# ===================== YUM / repodata / 自定义缓存数据

- name: "[os_yum.yml] repodata / 自定义缓存数据"
  include_tasks: "os_yum_repodata_custom.yml"
  when:
    - os_yum_repodata_custom_enabled

# ===================== YUM / repodata / 本地 ISO

- name: "[os_yum.yml] repodata / 本地 ISO"
  include_tasks: "os_yum_repodata_local_iso.yml"
  when:
    - os_yum_repodata_local_iso_enabled

# ===================== YUM / repodata / 局域网络

- name: "[os_yum.yml] repodata / 局域网络"
  include_tasks: "os_yum_repodata_local_network.yml"
  when:
    - os_yum_repodata_local_network_enabled

# ===================== YUM / repodata / 公共网络

- name: "[os_yum.yml] repodata / 公共网络"
  include_tasks: "os_yum_repodata_public_network.yml"
  when:
    - os_yum_repodata_public_network_enabled

# ===================== YUM / repodata / makecache

- name: "[os_yum.yml] YUM / makecache"
  shell: |
    yum makecache

- name: "[os_yum.yml] YUM / install"
  yum:
    disable_gpg_check: yes
    state: present
    name: "{{ os_yum__install_list }}"
