- name: "[Data Guard] 备库配置 / 密码文件"
  copy:
    owner: oracle
    group: oinstall
    mode: 0644
    backup: yes
    remote_src: yes
    src: "{{ dg_source__passwordfile }}"
    dest: "{{ dir__oracle_home }}/dbs/orapw{{ oracle_sid }}"

- name: "[Data Guard] 备库配置 / RMAN / 脚本文件"
  copy:
    owner: oracle
    group: oinstall
    mode: 0755
    backup: yes
    src: "rman_standby.rman"
    dest: "{{ dir__oracle_upload_sql_file }}/rman_standby.rman"

- name: "[Data Guard] 备库配置 / RMAN / 执行"
  shell: |
    su - oracle -c "rman target sys/{{ oracle_sys_password }}@{{ dg_db_unique_name_source }} auxiliary sys/{{ oracle_sys_password }}@{{ dg_db_unique_name_target }} log={{ dg_rman_logfile }} cmdfile={{ dir__oracle_upload_sql_file }}/rman_standby.rman"
  become: yes
  become_user: root
  become_method: sudo

- name: "上传查询主库段日志文件大小的SQL"
  copy:
    owner: oracle
    group: oinstall
    mode: 0755
    src: "logfile_bytes_primary.sql"
    dest: "{{ dir__oracle_upload_sql_file }}/logfile_bytes_primary.sql"

- name: "上传查询主库段日志文件大小的SHELL"
  template:
    owner: oracle
    group: oinstall
    mode: 0755
    src: "run_logfile_bytes_primary.sh.j2"
    dest: "{{ dir__oracle_upload_sql_file }}/run_logfile_bytes_primary.sh"

- name: "[Data Guard] 从主库获取 日志文件的大小 并将备库的 STANDBY LOGFILE 设为一样的大小"
  shell: |
    {{ dir__oracle_upload_sql_file }}/run_logfile_bytes_primary.sh
  register: standby_logfile_size
  become: yes
  become_user: root
  become_method: sudo
  when:
    - standby_logfile_size_automatic_sync_with_primary

- name: "[Data Guard] 备库配置 / Standby Logfile / SQL"
  template:
    owner: oracle
    group: oinstall
    mode: 0755
    src: "dg_standby_logfile.sql.j2"
    dest: "{{ dir__oracle_upload_sql_file }}/dg_standby_logfile.sql"

- name: "[Data Guard] 备库配置 / Standby Logfile / SQL / Shell"
  template:
    owner: oracle
    group: oinstall
    mode: 0755
    src: "run_dg_standby_logfile.sh.j2"
    dest: "{{ dir__oracle_upload_sql_file }}/run_dg_standby_logfile.sh"

- name: "[Data Guard] 备库配置 / Standby Logfile / SQL / Execute"
  shell: |
    {{ dir__oracle_upload_sql_file }}/run_dg_standby_logfile.sh
  become: yes
  become_user: root
  become_method: sudo
