- name: "[oracle_db_instance.yml] dbca / post-install / sql files / upload"
  copy:
    backup: yes
    force: yes
    owner: oracle
    group: oinstall
    mode: 0755
    src: "sql_files/{{ item }}"
    dest: "{{ dir__oracle_upload_sql_file }}/{{ item }}"
  with_items: "{{ oracle_db_instance__post_install__sqlfile_list }}"

- name: "[oracle_db_instance.yml] dbca / post-install / sql files / shell file"
  template:
    backup: yes
    owner: oracle
    group: oinstall
    mode: 0755
    src: "sql_files/post_install__sql_execute.sh.j2"
    dest: "{{ dir__oracle_upload_sql_file }}/post_install__sql_execute.sh"

- name: "[oracle_db_instance.yml] dbca / post-install / execute"
  shell: |
    {{ dir__oracle_upload_sql_file }}/post_install__sql_execute.sh
  become: yes
  become_user: root
  become_method: sudo
