- name: "Oracle Database software: 上传安装介质"
  unarchive:
    owner: oracle
    group: oinstall
    mode: 0755
    src: "{{ oracle_upload_install_media__file_install_media_db }}"
    dest: "{{ dir__oracle_home }}"
  when:
    - db_oracle_software__enabled_oracle_install

- name: "Oracle 补丁包: 上传安装介质"
  unarchive:
    owner: oracle
    group: oinstall
    mode: 0777
    src: "{{ item }}"
    dest: "{{ dir__oracle_upload_oracle_installmedia_patch }}"
  with_items: "{{ oracle_upload_install_media__file_install_media_patch_list }}"
  when:
    - db_oracle_software__enabled_patch_install
